// Auto-generated by PWA builder script.
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.0.0/workbox-sw.js');

if (workbox) {
    console.log(`Workbox is loaded.`);
    
    self.addEventListener('message', (event) => {
      if (event.data && event.data.type === 'SKIP_WAITING') {
        console.log('Service Worker received SKIP_WAITING message, activating now.');
        self.skipWaiting();
      }
    });

    workbox.precaching.precacheAndRoute([
    {
        "url": "icon-72.png",
        "revision": "1033e0e8713c8ff3334f9d302db6a4a6"
    },
    {
        "url": "icon-96.png",
        "revision": "bcf331c2d428c25d14d630b271ec142f"
    },
    {
        "url": "icon-128.png",
        "revision": "67cbb2c28cf3b0f6914155a89d916933"
    },
    {
        "url": "icon-144.png",
        "revision": "fddd2eec1c66ba813114fd3dd950390c"
    },
    {
        "url": "icon-152.png",
        "revision": "8c15e3f17b31cf226977e6d48444f783"
    },
    {
        "url": "icon-192.png",
        "revision": "f73d63f7505be28568e41f31ab76254a"
    },
    {
        "url": "icon-384.png",
        "revision": "49b0e172e2fa871ad2253aafb5fbeacf"
    },
    {
        "url": "icon-512.png",
        "revision": "1ea8bee8f8039d84d4455da02a1d6676"
    },
    {
        "url": "favicon.ico",
        "revision": "30229f8b2635461099204e6a4f5b42bf"
    },
    {
        "url": ".gitattributes",
        "revision": "05bdb783ee6514c8c072e47680af8ff7"
    },
    {
        "url": "build pwa make html app offline and installable yasin best working re-run this for updates best for html only.pyw",
        "revision": "a9f12964bddf9071fc97e333b587f108"
    },
    {
        "url": "index.html",
        "revision": "ed892af1da867918b927801d5d98820d"
    },
    {
        "url": "logo.png",
        "revision": "7a24ff5a43beb7153107cc63f7610c17"
    },
    {
        "url": "manifest.json",
        "revision": "91ad536adf9ef3a1e7fe401bab859455"
    },
    {
        "url": "offline.html",
        "revision": "ad17d01f02bb01615fbc0509f5aee82a"
    },
    {
        "url": "pwa-register.js",
        "revision": "3ec872e4f752840ad8f85922ff6cebe7"
    },
    {
        "url": "README.md",
        "revision": "7a4471fc74ea23588cc9d932e8376209"
    },
    {
        "url": "sw.js",
        "revision": "3b070ca879ec3e312b0cdba68ed2e58b"
    },
    {
        "url": "audio/sfx_die.wav",
        "revision": "629d572e913e69fd0a3b27a22ad90660"
    },
    {
        "url": "audio/sfx_hit.wav",
        "revision": "0941f389fbd65a06291a90dd17ef2e36"
    },
    {
        "url": "audio/sfx_point.wav",
        "revision": "5a6c267d6743faf5069536fda2553b27"
    },
    {
        "url": "audio/sfx_swooshing.wav",
        "revision": "3de704c77bf2eec51ba00897a8712355"
    },
    {
        "url": "audio/sfx_wing.wav",
        "revision": "4355dd665aa14ae22458f03e6b5643f8"
    },
    {
        "url": "img/.DS_Store",
        "revision": "194577a7e20bdcc7afbb718f502c134c"
    },
    {
        "url": "img/001-screenshot.png",
        "revision": "e551f663e22bb8bdba2660c8685f5fe4"
    },
    {
        "url": "img/001-wireframe.png",
        "revision": "66b1b59446c6f3d997af40e46d3e42c0"
    },
    {
        "url": "img/002-wireframe.png",
        "revision": "9e4a69ccde34829c1dd6dc55b6db5767"
    },
    {
        "url": "img/og-theme-2.png",
        "revision": "5438542557626c9814ef2162a19e2908"
    },
    {
        "url": "img/og-theme.png",
        "revision": "57213cdc773432526b4ed0386f41bc31"
    }
]);

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'style' || request.destination === 'script',
        new workbox.strategies.StaleWhileRevalidate({ cacheName: 'asset-cache' })
    );

    workbox.routing.registerRoute(
        ({request}) => request.destination === 'image',
        new workbox.strategies.CacheFirst({
            cacheName: 'image-cache',
            plugins: [ new workbox.expiration.ExpirationPlugin({ maxEntries: 60, maxAgeSeconds: 30 * 24 * 60 * 60 }) ],
        })
    );

    workbox.routing.setCatchHandler(async ({event}) => {
        if (event.request.destination === 'document') {
            return await caches.match('offline.html') || Response.error();
        }
        return Response.error();
    });

} else {
    console.log(`Workbox failed to load.`);
}